### ISSUE TITLE
Add "suiteId" for projects without single suite mode

### ISSUE THREAD

**Issue by boxblinkracer** [boxblinkracer/cypress-testrail#11]
It should be possible to provide the "suite_id" parameter.
Otherwise projects without the single suite mode cannot be used when creating runs from the integration

https://support.gurock.com/hc/en-us/articles/7077874763156-Runs#addrun

**Comment by boxblinkracer** [comment]
implemented in the master branch...not yet fully tested

**Comment by colcherica** [comment]
@boxblinkracer Short test done on my project and it's working properly, one small thing that an error is trow, but I think this is under investigation. 
![image](https://user-images.githubusercontent.com/20081012/209695703-6f1315f2-805a-4881-897a-8a62fbbf9097.png)

**Comment by boxblinkracer** [comment]
Hi there

this is amazing
thank you for letting me know

the other one is just from the new screenshot upload feature. it should already work, but theres a bug somewhere that this error happens...but yeah...not yet done haha :)

**Comment by boxblinkracer** [comment]
hi there
just published 2.5.0 with suiteId :)
all tested from my side and looks good
