### ISSUE TITLE
Is cypress-testrail compatible with Cypress 9.7?

### ISSUE THREAD

**Issue by sultanzarif** [boxblinkracer/cypress-testrail#2]
Hi Christian, thanks for the repo. It seems it is great repo. I wonder if we can use [cypress-testrail](https://github.com/boxblinkracer/cypress-testrail) on Cypress 9.x? Any thoughts?

**Comment by boxblinkracer** [comment]
Hi

yep its working, just tried it :)

**Comment by boxblinkracer** [comment]
oh and thanks for the kind words :)
