### ISSUE TITLE
cypress cucumber scenarios integration ? 

### ISSUE THREAD

**Issue by MrNeo28** [boxblinkracer/cypress-testrail#20]
Thanks for you package, its wonderful. Any support of cypress cucucmber pre-processer ?

**Comment by vincentpalita** [comment]
You just need to include a testcase number in the title of your scenario, such as:

`Scenario: C11619: The user "USER_ADMIN" should be able to login to the admin area`

**Comment by boxblinkracer** [comment]
perfect, that makes sense
could you probably create as an entry in the README about this? im not using cucumber yet and that would indeed help

**Comment by boxblinkracer** [comment]
Hi

this is finally done
so i will continue in the other ticket: https://github.com/boxblinkracer/cypress-testrail/issues/14

...and close this one :)
