### ISSUE TITLE
I'd like to be able to use this tool to both create a new test run and use that test run for the results. 

### ISSUE THREAD

**Issue by williamatpaper** [boxblinkracer/cypress-testrail#21]
This could be done by allowing me to configure this option.

https://github.com/boxblinkracer/cypress-testrail/blob/3258c75c00575882dde8e07d06941e3748d27833/src/components/TestRail/TestRail.js#L31

**Comment by boxblinkracer** [comment]
Hi there
ähm...so what it basically does, is it starts without tests in that new create run
then when cypress runs, those tests will be added before the result is sent

so if include_all is TRUE, then i think all test cases are automatically in that test run, even though they are not existing in cypress.

is that what you need in the end? a mixed test run where some is automatically done through cypress and the rest is done manually? (i basically do the same with another tool and testrail, but then I have a manual prepared test run and fire against that run ID)

**Comment by williamatpaper** [comment]
Hmm.. I just want to be able to adjust this value so that the include_all variable is customizable. Here are there api docs: https://support.testrail.com/hc/en-us/articles/7077874763156-Runs#addrun

But yes, currently we create a new test run (with this parameter set to true, because it's defaulted that way) and then use that test run for the results of the cypress run.

I'd like to not have to do the manual step to create a new test run before running my cypress suite.

**Comment by boxblinkracer** [comment]
thank you for your contribution on this
coming with next release :)

**Comment by boxblinkracer** [comment]
released in 2.7.0
