### ISSUE TITLE
How to register a plugin in Cypress V10 and above

### ISSUE THREAD

**Issue by shashank-mhegde** [boxblinkracer/cypress-testrail#26]
In cypress V10 and above, we dont have default plugins folder. 

```
 setupNodeEvents(on, config)
    {
        return require('./cypress/plugins/index.js')(on, config)
    }
```
Adding above in cypress.config file is giving below error

<img width="509" alt="image" src="https://github.com/boxblinkracer/cypress-testrail/assets/74168071/90b48477-9a70-4ff0-ac68-fcccf7855dcf">

 How do we register this plugin ?. Do we need to add the plugins folder

**Comment by boxblinkracer** [comment]
hi there

thanks for your message

you can just create it, or even drop the registration right in that setupNodeEvents, should also work, because on and config exists). I also use it on later Cypress setups :) so that works
