### ISSUE TITLE
Plugin won't work if Cypress' experimentalInteractiveRunEvents flag is not turned on when using Cypress Open mode

### ISSUE THREAD

**Issue by vincentpalita** [boxblinkracer/cypress-testrail#28]
Hello!

First of all, thank you for this plugin!
I have been struggling to find a way to make it work. After some debugging I found out that the "experimentalInteractiveRunEvents" option needs to be enabled when using Cypress with open mode as documentation says here: https://docs.cypress.io/api/plugins/before-run-api

Without that flag on, it won't work at all.
Is it something you are aware of?

I am using Cypress v12.7.0

**Comment by vincentpalita** [comment]
After some more digging, I think the readme should state that this should be used only in run mode. 
Would you like me to propose a PR?

**Comment by boxblinkracer** [comment]
Hi 

thank you for your kind words and also the debugging
you are right, this is actually meant for the run-mode only....and you're right with "its not in the readme" 
I totally forgot about this

what is interesting is,...it also works in UI mode using that flag? NICE! any downsides?

If you have time, I would be happy about a PR...I think your work should at least show you in the contributors list :)

**Comment by boxblinkracer** [comment]
thank you @Jorgexyx for the PR :)

**Comment by vincentpalita** [comment]
thank you @Jorgexyx, been very busy since my last comment and haven't had the chance to even reply to @boxblinkracer comment.
