### ISSUE TITLE
400 Bad Request >> Missing Error received when try to publish results to testrail

### ISSUE THREAD

**Issue by colcherica** [boxblinkracer/cypress-testrail#29]
cypress-testrail (latest version): 2.7.1 
Cypress version: 12.14.0

After test suite is run with success and try to publish the results on testrail the following error is received: 
"Could not send list of TestRail results: 400 Bad Request >> Missing Error" 
![Screenshot from 2023-06-19 14-52-03](https://github.com/boxblinkracer/cypress-testrail/assets/20081012/853d4b5e-3079-47b1-ae6e-007a695d59f6)

**Comment by colcherica** [comment]
fixed due to bad configuration into domain

**Comment by boxblinkracer** [comment]
hi there
a cool
what was your wrong config? maybe i can add a check for it :)

**Comment by colcherica** [comment]
I had something like: testrail.com ' instead of testrail.com

**Comment by boxblinkracer** [comment]
ok thats weird, i thought i have already removed leading http schemes if accidentally provided 
ill double check 

but thanks, great its working now
