### ISSUE TITLE
Installing as a package dependency fails

### ISSUE THREAD

**Issue by gregorRW** [boxblinkracer/cypress-testrail#3]
Once the package is installed and added as a dev-dependency, it can't be reinstalled as packages-lock.json doesn't contain dependencies:

```
   "node_modules/cypress-tags": {
      "version": "1.0.2",
      "resolved": "https://registry.npmjs.org/cypress-tags/-/cypress-tags-1.0.2.tgz",
      "integrity": "sha512-1BAay8ADYIHeABFO7fMboGihk8KUDmi31egO9fsrfdFZ+sf10oyoep+8HgEEq5VWTXJNewdZK0gwz5ShOD7xCA==",
      "dev": true,
      "dependencies": {
        "@cypress/browserify-preprocessor": "^3.0.1",
        "boolean-parser": "0.0.2",
        "through": "^2.3.8"
      },
      "peerDependencies": {
        "cypress": ">= 10.0.0"
      }
    },
    "node_modules/cypress-testrail": {
      "version": "2.1.1",
      "resolved": "https://registry.npmjs.org/cypress-testrail/-/cypress-testrail-2.1.1.tgz",
      "integrity": "sha512-xvdB3jiXSKZadS161+vmOy5Q47c3BhpwzGBP7Ql5VkhLu2+Sti7HtqlmB2wx9AkFyW+wliN7YLGotDwkAi4xiw==",
      "dev": true
    },
```

As you can see, its missing "dependencies" so they don't get installed.

Disclaimer - could only be my insufficient JS/npm knowledge and I'm messing something up.

**Comment by boxblinkracer** [comment]
Hi

aehm. i dont think this has to do with the package. im using it in a couple of projects and didnt have that problem. 

could you probably write me the steps to reproduce. then im trying to help you as good as possible 

thanks

**Comment by gregorRW** [comment]
Hey!

I start with the following package.json (no package-lock.json and node_modules empty) and `npm install`

```
{
  "devDependencies": {
    "@simonsmith/cypress-image-snapshot": "^6.0.0",
    "cypress": "^10.8.0",
    "cypress-localstorage-commands": "^2.2.1",
    "cypress-tags": "^1.0.2",
    "typescript": "^4.8.3"
  }
}

```

then run: `npm i cypress-testrail --save-dev`
which outputs:
```
% npm i cypress-testrail --save-dev


added 1 package, and audited 763 packages in 1s

94 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
This is the first hint - added only 1 package.
Now if I try to run cypress, I get:
<img width="858" alt="Screenshot 2022-10-01 at 15 35 17" src="https://user-images.githubusercontent.com/29927193/193412132-ebfb535e-4f7e-4299-ac78-eced6df24987.png">

Looking at the package-lock.json that was generated I only see:
```
    "node_modules/cypress-testrail": {
      "version": "2.1.1",
      "resolved": "https://registry.npmjs.org/cypress-testrail/-/cypress-testrail-2.1.1.tgz",
      "integrity": "sha512-xvdB3jiXSKZadS161+vmOy5Q47c3BhpwzGBP7Ql5VkhLu2+Sti7HtqlmB2wx9AkFyW+wliN7YLGotDwkAi4xiw==",
      "dev": true
    },
```
which is missing the dependencies.

OS: MacOS
Npm: 8.19.2

**Comment by boxblinkracer** [comment]
aaaaa thanks

yes i saw that yesterday
axios is missing. 

so in other words. when installing it, axios is not installed automatically since a while somehow

yep i know that

if you install axios with npm then it works. 

thanks for pointing it out

**Comment by gregorRW** [comment]
Yeah, workaround is to add dependencies directly into the root packages.json

Looking at the packages.json for the module (and comparing to the other cypress-plugins), I think 

```
    "devDependencies": {
        "@babel/eslint-parser": "^7.18.2",
        "@babel/preset-env": "^7.18.2",
        "axios": "^0.27.2",
        "babel-jest": "^28.1.1",
        "eslint": "^8.18.0",
        "jest": "^28.1.1",
        "prettier": "2.7.1"
    }
```

should just become "dependencies":
```
    "dependencies": {
        "@babel/eslint-parser": "^7.18.2",
        "@babel/preset-env": "^7.18.2",
        "axios": "^0.27.2",
        "babel-jest": "^28.1.1",
        "eslint": "^8.18.0",
        "jest": "^28.1.1",
        "prettier": "2.7.1"
    }
```

But as said before - I'm not into NPM so I'm probably saying something stupid here :D

**Comment by boxblinkracer** [comment]
Hi

just fixed it with 2.2.0
axios is now inside :)

can you double check?

**Comment by gregorRW** [comment]
Yes, now it works as expected! Thank you sir!

**Comment by boxblinkracer** [comment]
perfect
thanks for letting me know @gregorRW  :)
