### ISSUE TITLE
How to send result to testrail with many runId within once?

### ISSUE THREAD

**Issue by natthakitdoppiotech** [boxblinkracer/cypress-testrail#30]
I need to send test result automation to testrail but we have many runId. How to send result to testrail with many runId within once?

**Comment by boxblinkracer** [comment]
hi there

i havent thought about that scenario
so at the moment you would need to restart it for a separate run

in your case, you would need to be able to configure a LIST of runIds, is that correct?
and every result will be sent to all configured runIDs?

**Comment by natthakitdoppiotech** [comment]
You mean fix this on cypress env right? I try it and can't sent result to testrail. It don't know runIds and required suitId.
"testrail": {
    "domain": "xxxxxxxxx",
    "username": "xxxxxxxxx",
    "password": "xxxxxxxxx",
    "screenshots": true,
    "projectId": "xx",
    _**"runIds": ["R123", "R456"],**_
    "milestoneId": "M21",
    "runName": "",
    "runIncludeAll": false,
    "closeRun": false
}

**Comment by boxblinkracer** [comment]
hi there
yes exactly, but not fixing it, more requesting it as a feature :)

this does not work yet, I would need to develop it :)

so thats my basic question, you would need something like this, right?

`"runIds": ["R123", "R456"],`

thanks

**Comment by boxblinkracer** [comment]
hi there
so it's implemented
it worked already, but final testing phase is still open

if you want you can try it in dev-master :) (readme is already updated too for docs)

**Comment by natthakitdoppiotech** [comment]
Thank you, I will try it and  get back to you : )

**Comment by boxblinkracer** [comment]
released in v2.8.0 :)
