### ISSUE TITLE
How to auto mark `.skip` cases in testrail reports?

### ISSUE THREAD

**Issue by praveen-nj** [boxblinkracer/cypress-testrail#31]
Right the cases that are skipped on purpose are not being reported at all to testrail. 
1. Is there a reason for that?
2. Would it be possible to mark them as well?

**Comment by boxblinkracer** [comment]
hi there

you mean if a cypress test has the ".skip" option added?

didnt think about that,
i will try to figure out if its possible and maybe set it to "blocked" in testrail

did i understand you correctly?

**Comment by praveen-nj** [comment]
Hi,

Yes, you got it right.
Instead of maybe try `skip` (which I believe is one of the default statuses)

And, thank you.

**Comment by boxblinkracer** [comment]
ok perfect

...yeah i need to look it up (one day i also need to add a custom mapping configuration for a status)
ill add it to the roadmap for the next dev-session :)

great idea, thanks for this

**Comment by praveen-nj** [comment]
Awesome, thanks.

**Comment by boxblinkracer** [comment]
alright added in main branch
not yet completely tested, will do QA phase before release
but you could try it if you want

**Comment by boxblinkracer** [comment]
released in v2.8.0 :)
