### ISSUE TITLE
Screenshots on failed test are not being send to testrail on cypress v13

### ISSUE THREAD

**Issue by pablosmalys** [boxblinkracer/cypress-testrail#49]
After update to cypress v13, the screenshots are not being send to test rail. Only output error message is send to Testrail. 

On both projects is "screenshots" in cypress.env.json file is set to TRUE

![image](https://github.com/boxblinkracer/cypress-testrail/assets/124821772/e3b11f47-bbca-453c-b54a-f0c457815f3e)

**Comment by boxblinkracer** [comment]
Hi there

thanks for reporting
the structure has indeed changed, the latest dev-master has a fix
could you double check with it please?

thanks

**Comment by pablosmalys** [comment]
hi, I just tried and screenshots seems still not be sending to testrail. 

Version of plugin is 2.8.1. 

Just to be sure, do I need to reinstall plugin or some specific steps to perform to have fix?

**Comment by boxblinkracer** [comment]
i tried it myself and it worked
can you double check the version you have

your Reporter.js should have these adjustments for cypress 13
https://github.com/boxblinkracer/cypress-testrail/blob/e8e287ac355094116790b6d4bf602257f6baea5e/src/Reporter.js#L330

and then "screenshots" variable to true and it worked for me in run mode

**Comment by pablosmalys** [comment]
well yeah, when I replaced reported.js file with updated code then it works. Thanks for resolving.
<img width="1199" alt="image" src="https://github.com/boxblinkracer/cypress-testrail/assets/124821772/2e838dde-ac05-4b3e-ad9a-818c95edd102">

**Comment by boxblinkracer** [comment]
NICE!!!
thank you for the feedback

then it will come with the next version

**Comment by boxblinkracer** [comment]
released in 2.8.2
