### ISSUE TITLE
Allow API Key for authentication

### ISSUE THREAD

**Issue by HAL9000Thomas** [boxblinkracer/cypress-testrail#55]
I would like to use an API key instead of my user credentials. It says
Could not create TestRail run for project P6: 401 Unauthorized >> Authentication failed: invalid or missing user/password or session cookie.
It works with my main username credentials. Are the API keys supported?

**Comment by boxblinkracer** [comment]
Hi

that's a good one
Ill add it ass task so it gets done :)

thank you

**Comment by boxblinkracer** [comment]
Hi

I just gave it a try and this already works.
TestRail says you can use a password or a given API Key in the password field

can you try it :)

**Comment by boxblinkracer** [comment]
released with 2.10.0
