### ISSUE TITLE
Create test cases for tests without test case id in testrail

### ISSUE THREAD

**Issue by HAL9000Thomas** [boxblinkracer/cypress-testrail#56]
My test rail project has around 100 test cases. Half of them are automated by Cypress. So I can match only 50% of the test cases to cypress tests (by setting testcase id). The results are reported to testrail if I execute cypress, but only testcases which are marked with a testcase number are generated. I would like to generate the other non automated test cases too so we can see what we should test manually. Is that possible?

**Comment by HAL9000Thomas** [comment]
Ok, just noticed I can achieve wanted behavior by using "runIncludeAll": true,

**Comment by boxblinkracer** [comment]
Hi

ok great

thank you for clearing things up

have a wonderful weekend
