### ISSUE TITLE
Can i obtain testrunID when cypress running?

### ISSUE THREAD

**Issue by ivanalami** [boxblinkracer/cypress-testrail#57]
"Can I obtain the testrunId when running Cypress in auto-create testrun mode (I am running Cypress without inputting a testrunID)?"

**Comment by boxblinkracer** [comment]
Hi there

aehm,...i think the created Run ID is actually displayed in the output

but do you need to obtain it in a technical way somehow?

**Comment by ivanalami** [comment]
Hi, thanks for respons.

I want to make an improvement where I can attach a link to a test run that has been created to Slack.

I think that if the test run is created while Cypress is running, it's not possible for me to hit the TestRun API and wait for the Cypress execution to finish, as there is a risk of having a newer test run that does not belong to the currently running Cypress.

So, is it possible for me to obtain the TestRun ID while running Cypress using the cypress-testrail plugin in CI?

**Comment by boxblinkracer** [comment]
Ok I got it thanks

so I could offer writing a temp. file that contains the run id
like
"created-run.txt"

then you can simply fetch and read that file while Cypress is running
sounds good?

the content would be the run ID.....do you want with or without leading"R"
so "R45" or "45"?

i think the URL in testrail is withour R, so number alone would be good?

**Comment by ivanalami** [comment]
amazing. Yah just number is enough. 
thank you so much for response

**Comment by boxblinkracer** [comment]
surprise
its done
you can use dev-master

and its even better, the created_run.json file contains some more useful data
so full json with stuff you can use

i hope you like it

**Comment by boxblinkracer** [comment]
released with 2.10.0
