### ISSUE TITLE
Automatic screenshot upload along with error log

### ISSUE THREAD

**Issue by praveen-nj** [boxblinkracer/cypress-testrail#9]

**Comment by boxblinkracer** [comment]
Hi

thank you for this

thats a great idea
ill add it to the todo

**Comment by praveen-nj** [comment]
Thank you.

If you could get the error log and the screenshot should be in the same testrail result entry, that'd be much helpful.

**Comment by boxblinkracer** [comment]
hi there
just did it,...and it looks promising.
should be released after christmas...but its already in dev-master (no guarantee yet) :)

**Comment by praveen-nj** [comment]
That's good to hear. Thank you very much.

**Comment by boxblinkracer** [comment]
hi there
just published 2.5.0 with this feature
please see the README for more :)

i will now close this ticket, thx for the great idea
